CREATE DATABASE IF NOT EXISTS edushare_db;
USE edushare_db;

CREATE TABLE IF NOT EXISTS NGUOIDUNG (
    MaND INT AUTO_INCREMENT PRIMARY KEY,
    HoTen VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    VaiTro ENUM('SinhVien', 'GiaoVien', 'Admin') DEFAULT 'SinhVien',
    TrangThai ENUM('HoatDong', 'BiKhoa') DEFAULT 'HoatDong',
    AvatarURL VARCHAR(255) DEFAULT NULL,
    Tuoi INT DEFAULT NULL,
    GioiTinh ENUM('Nam', 'Nu', 'Khac') DEFAULT 'Khac',
    DiaChi VARCHAR(255) DEFAULT NULL,
    TruongHoc VARCHAR(255) DEFAULT NULL,
    KhoaNganh VARCHAR(255) DEFAULT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TAILIEU (
    MaTL INT AUTO_INCREMENT PRIMARY KEY,
    TenTL VARCHAR(255) NOT NULL,
    MoTa TEXT,
    FileURL VARCHAR(255) NOT NULL,
    PreviewURL VARCHAR(255) DEFAULT NULL,
    LoaiFile VARCHAR(10) NOT NULL,
    MaMonHoc INT NOT NULL,
    MaND_NguoiDang INT NOT NULL,
    TrangThaiKiemDuyet ENUM('ChoDuyet', 'DaDuyet', 'TuChoi') DEFAULT 'ChoDuyet',
    LyDoTuChoi TEXT DEFAULT NULL,
    PhanHoiTuChoi TEXT DEFAULT NULL,
    LaTaiLieuChinhThuc BOOLEAN DEFAULT FALSE,
    LaTaiLieuDocQuyen BOOLEAN DEFAULT FALSE,
    SoLuotTai INT DEFAULT 0,
    SoLuotXem INT DEFAULT 0,
    NgayDang DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaND_NguoiDang) REFERENCES NGUOIDUNG(MaND)
);

CREATE TABLE IF NOT EXISTS MONHOC (
    MaMonHoc INT AUTO_INCREMENT PRIMARY KEY,
    TenMonHoc VARCHAR(255) NOT NULL,
    CapHoc VARCHAR(100) DEFAULT 'Khac',
    TrangThai ENUM('HoatDong', 'TamAn', 'DaXoa') DEFAULT 'HoatDong'
);

CREATE TABLE IF NOT EXISTS DEXUAT_MONHOC (
    MaDeXuat INT AUTO_INCREMENT PRIMARY KEY,
    TenMonHoc VARCHAR(255) NOT NULL,
    CapHoc VARCHAR(100) DEFAULT 'Khac',
    MoTa TEXT,
    LyDo TEXT,
    MaND_DeXuat INT NOT NULL,
    TrangThai ENUM('ChoDuyet', 'DaDuyet', 'TuChoi') DEFAULT 'ChoDuyet',
    LyDoTuChoi TEXT DEFAULT NULL,
    MaMonHocDaTao INT DEFAULT NULL,
    MaND_Duyet INT DEFAULT NULL,
    NgayDeXuat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayDuyet DATETIME DEFAULT NULL,
    FOREIGN KEY (MaND_DeXuat) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaMonHocDaTao) REFERENCES MONHOC(MaMonHoc),
    FOREIGN KEY (MaND_Duyet) REFERENCES NGUOIDUNG(MaND)
);

CREATE TABLE IF NOT EXISTS THONGBAO (
    MaTB INT AUTO_INCREMENT PRIMARY KEY,
    MaND INT NOT NULL,
    NoiDung TEXT NOT NULL,
    LoaiTB VARCHAR(50) DEFAULT 'HeThong',
    DaDoc BOOLEAN DEFAULT FALSE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND)
);

CREATE TABLE IF NOT EXISTS BOOKMARK (
    MaND INT NOT NULL,
    MaTL INT NOT NULL,
    NgayLuu DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND, MaTL),
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaTL) REFERENCES TAILIEU(MaTL)
);

CREATE TABLE IF NOT EXISTS DANHGIA (
    MaND INT NOT NULL,
    MaTL INT NOT NULL,
    SoSao INT NOT NULL CHECK (SoSao BETWEEN 1 AND 5),
    NgayDanhGia DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND, MaTL),
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaTL) REFERENCES TAILIEU(MaTL)
);

CREATE TABLE IF NOT EXISTS BINHLUAN (
    MaBL INT AUTO_INCREMENT PRIMARY KEY,
    MaND INT NOT NULL,
    MaTL INT NOT NULL,
    NoiDung TEXT NOT NULL,
    MaBL_Cha INT DEFAULT NULL,
    NgayBinhLuan DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaTL) REFERENCES TAILIEU(MaTL),
    FOREIGN KEY (MaBL_Cha) REFERENCES BINHLUAN(MaBL)
);

CREATE TABLE IF NOT EXISTS BAOCAOVIPHAM (
    MaBC INT AUTO_INCREMENT PRIMARY KEY,
    MaND INT NOT NULL,
    MaTL INT NOT NULL,
    LyDo TEXT NOT NULL,
    TrangThai ENUM('ChoXuLy', 'DaXuLy', 'TuChoi') DEFAULT 'ChoXuLy',
    NgayBaoCao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaTL) REFERENCES TAILIEU(MaTL)
);

CREATE TABLE IF NOT EXISTS NHOM (
    MaNhom INT AUTO_INCREMENT PRIMARY KEY,
    TenNhom VARCHAR(255) NOT NULL,
    MoTa TEXT,
    MaND_QuanTri INT NOT NULL,
    MaMonHoc INT,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaND_QuanTri) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaMonHoc) REFERENCES MONHOC(MaMonHoc)
);

CREATE TABLE IF NOT EXISTS THANHVIEN_NHOM (
    MaND INT NOT NULL,
    MaNhom INT NOT NULL,
    VaiTroTrongNhom ENUM('QuanTri', 'ThanhVien') DEFAULT 'ThanhVien',
    NgayThamGia DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND, MaNhom),
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaNhom) REFERENCES NHOM(MaNhom)
);

CREATE TABLE IF NOT EXISTS TAILIEU_NHOM (
    MaTL INT NOT NULL,
    MaNhom INT NOT NULL,
    NgayChiaSe DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaTL, MaNhom),
    FOREIGN KEY (MaTL) REFERENCES TAILIEU(MaTL),
    FOREIGN KEY (MaNhom) REFERENCES NHOM(MaNhom)
);

CREATE TABLE IF NOT EXISTS THEODOI (
    MaND_TheoDoi INT NOT NULL,
    MaND_DuocTheoDoi INT NOT NULL,
    NgayTheoDoi DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND_TheoDoi, MaND_DuocTheoDoi),
    FOREIGN KEY (MaND_TheoDoi) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaND_DuocTheoDoi) REFERENCES NGUOIDUNG(MaND)
);

CREATE TABLE IF NOT EXISTS NGUOIDUNG_MONHOC (
    MaND INT NOT NULL,
    MaMonHoc INT NOT NULL,
    NgayTheoDoi DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND, MaMonHoc),
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaMonHoc) REFERENCES MONHOC(MaMonHoc)
);

CREATE TABLE IF NOT EXISTS TRUONGHOC (
    MaTruong INT AUTO_INCREMENT PRIMARY KEY,
    TenTruong VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS KHOANGANH (
    MaKhoa INT AUTO_INCREMENT PRIMARY KEY,
    TenKhoa VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS RESET_PASSWORD_OTP (
    Email VARCHAR(255) PRIMARY KEY,
    OTP VARCHAR(10) NOT NULL,
    ExpiresAt DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS GIAODICH_NAPXU (
    MaGD INT AUTO_INCREMENT PRIMARY KEY,
    MaND INT NOT NULL,
    SoTien INT NOT NULL,
    SoXu INT NOT NULL,
    TrangThai ENUM('ChoDuyet', 'DaDuyet', 'TuChoi') DEFAULT 'ChoDuyet',
    MaND_Duyet INT DEFAULT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayDuyet DATETIME DEFAULT NULL,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaND_Duyet) REFERENCES NGUOIDUNG(MaND)
);
