CREATE DATABASE IF NOT EXISTS edushare_db;
USE edushare_db;

CREATE TABLE IF NOT EXISTS NGUOIDUNG (
    MaND INT AUTO_INCREMENT PRIMARY KEY,
    HoTen VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    VaiTro ENUM('SinhVien', 'GiaoVien', 'Admin') DEFAULT 'SinhVien',
    TrangThai ENUM('HoatDong', 'BiKhoa') DEFAULT 'HoatDong',
    AvatarURL VARCHAR(255) DEFAULT NULL,
    Tuoi INT DEFAULT NULL,
    SoDuXu INT DEFAULT 0,
    GioiTinh ENUM('Nam', 'Nu', 'Khac') DEFAULT 'Khac',
    DiaChi VARCHAR(255) DEFAULT NULL,
    TruongHoc VARCHAR(255) DEFAULT NULL,
    KhoaNganh VARCHAR(255) DEFAULT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    AuthType ENUM('Local', 'Google', 'Facebook') DEFAULT 'Local',
    TwoFactorSecret VARCHAR(255) DEFAULT NULL,
    IsTwoFactorEnabled BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS DANHHIEU (
    MaDanhHieu INT AUTO_INCREMENT PRIMARY KEY,
    TenDanhHieu VARCHAR(255) NOT NULL,
    IconClass VARCHAR(255) NOT NULL,
    MauSac VARCHAR(50) NOT NULL,
    MoTa TEXT,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS NGUOIDUNG_DANHHIEU (
    MaND INT NOT NULL,
    MaDanhHieu INT NOT NULL,
    LaDanhHieuChinh BOOLEAN DEFAULT FALSE,
    NgayNhan DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND, MaDanhHieu),
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE,
    FOREIGN KEY (MaDanhHieu) REFERENCES DANHHIEU(MaDanhHieu) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TAILIEU (
    MaTL INT AUTO_INCREMENT PRIMARY KEY,
    TenTL VARCHAR(255) NOT NULL,
    MoTa TEXT,
    FileURL VARCHAR(255) NOT NULL,
    PreviewURL VARCHAR(255) DEFAULT NULL,
    LoaiFile VARCHAR(10) NOT NULL,
    MaMonHoc INT NOT NULL,
    MaND_NguoiDang INT NOT NULL,
    TrangThaiKiemDuyet ENUM('ChoDuyet', 'DaDuyet', 'TuChoi') DEFAULT 'ChoDuyet',
    LyDoTuChoi TEXT DEFAULT NULL,
    PhanHoiTuChoi TEXT DEFAULT NULL,
    LaTaiLieuChinhThuc BOOLEAN DEFAULT FALSE,
    LaTaiLieuDocQuyen BOOLEAN DEFAULT FALSE,
    FileHash VARCHAR(255) DEFAULT NULL,
    GiaXu INT DEFAULT 0,
    SoLuotTai INT DEFAULT 0,
    SoLuotXem INT DEFAULT 0,
    NgayDang DATETIME DEFAULT CURRENT_TIMESTAMP,
    TextSEO TEXT,
    IsDeleted BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (MaND_NguoiDang) REFERENCES NGUOIDUNG(MaND)
);

CREATE TABLE IF NOT EXISTS MONHOC (
    MaMonHoc INT AUTO_INCREMENT PRIMARY KEY,
    TenMonHoc VARCHAR(255) NOT NULL,
    CapHoc VARCHAR(100) DEFAULT 'Khac',
    TrangThai ENUM('HoatDong', 'TamAn', 'DaXoa') DEFAULT 'HoatDong',
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DEXUAT_MONHOC (
    MaDeXuat INT AUTO_INCREMENT PRIMARY KEY,
    TenMonHoc VARCHAR(255) NOT NULL,
    CapHoc VARCHAR(100) DEFAULT 'Khac',
    MoTa TEXT,
    LyDo TEXT,
    MaND_DeXuat INT NOT NULL,
    TrangThai ENUM('ChoDuyet', 'DaDuyet', 'TuChoi') DEFAULT 'ChoDuyet',
    LyDoTuChoi TEXT DEFAULT NULL,
    MaMonHocDaTao INT DEFAULT NULL,
    MaND_Duyet INT DEFAULT NULL,
    NgayDeXuat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayDuyet DATETIME DEFAULT NULL,
    FOREIGN KEY (MaND_DeXuat) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaMonHocDaTao) REFERENCES MONHOC(MaMonHoc),
    FOREIGN KEY (MaND_Duyet) REFERENCES NGUOIDUNG(MaND)
);

CREATE TABLE IF NOT EXISTS THONGBAO (
    MaTB INT AUTO_INCREMENT PRIMARY KEY,
    MaND INT NOT NULL,
    NoiDung TEXT NOT NULL,
    LoaiTB VARCHAR(50) DEFAULT 'HeThong',
    DaDoc BOOLEAN DEFAULT FALSE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND)
);

CREATE TABLE IF NOT EXISTS BOOKMARK (
    MaND INT NOT NULL,
    MaTL INT NOT NULL,
    NgayLuu DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND, MaTL),
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaTL) REFERENCES TAILIEU(MaTL)
);

CREATE TABLE IF NOT EXISTS DANHGIA (
    MaND INT NOT NULL,
    MaTL INT NOT NULL,
    SoSao INT NOT NULL CHECK (SoSao BETWEEN 1 AND 5),
    NgayDanhGia DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND, MaTL),
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaTL) REFERENCES TAILIEU(MaTL)
);

CREATE TABLE IF NOT EXISTS BINHLUAN (
    MaBL INT AUTO_INCREMENT PRIMARY KEY,
    MaND INT NOT NULL,
    MaTL INT NOT NULL,
    NoiDung TEXT NOT NULL,
    DaGhim BOOLEAN DEFAULT FALSE,
    MaBL_Cha INT DEFAULT NULL,
    NgayBinhLuan DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaTL) REFERENCES TAILIEU(MaTL),
    FOREIGN KEY (MaBL_Cha) REFERENCES BINHLUAN(MaBL)
);

CREATE TABLE IF NOT EXISTS BAOCAOVIPHAM (
    MaBC INT AUTO_INCREMENT PRIMARY KEY,
    MaND INT NOT NULL,
    MaTL INT NOT NULL,
    LyDo TEXT NOT NULL,
    TrangThai ENUM('ChoXuLy', 'DaXuLy', 'TuChoi') DEFAULT 'ChoXuLy',
    NgayBaoCao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaTL) REFERENCES TAILIEU(MaTL)
);

CREATE TABLE IF NOT EXISTS NHOM (
    MaNhom INT AUTO_INCREMENT PRIMARY KEY,
    TenNhom VARCHAR(255) NOT NULL,
    MoTa TEXT,
    MaND_QuanTri INT NOT NULL,
    MaMonHoc INT,
    AnhBia VARCHAR(255) DEFAULT NULL,
    IsPrivate BOOLEAN DEFAULT FALSE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaND_QuanTri) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaMonHoc) REFERENCES MONHOC(MaMonHoc)
);

CREATE TABLE IF NOT EXISTS THANHVIEN_NHOM (
    MaND INT NOT NULL,
    MaNhom INT NOT NULL,
    VaiTroTrongNhom ENUM('QuanTri', 'PhoNhom', 'ThanhVien') DEFAULT 'ThanhVien',
    NgayThamGia DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND, MaNhom),
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE,
    FOREIGN KEY (MaNhom) REFERENCES NHOM(MaNhom) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS YEUCAUTHAMGIA_NHOM (
    MaND INT NOT NULL,
    MaNhom INT NOT NULL,
    NgayYeuCau DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND, MaNhom),
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE,
    FOREIGN KEY (MaNhom) REFERENCES NHOM(MaNhom) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TAILIEU_NHOM (
    MaTL INT NOT NULL,
    MaNhom INT NOT NULL,
    NgayChiaSe DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaTL, MaNhom),
    FOREIGN KEY (MaTL) REFERENCES TAILIEU(MaTL),
    FOREIGN KEY (MaNhom) REFERENCES NHOM(MaNhom)
);

CREATE TABLE IF NOT EXISTS BAIVIET_NHOM (
    MaBaiViet INT AUTO_INCREMENT PRIMARY KEY,
    MaND INT NOT NULL,
    MaNhom INT NOT NULL,
    NoiDung TEXT NOT NULL,
    NgayDang DATETIME DEFAULT CURRENT_TIMESTAMP,
    DaGhim BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE,
    FOREIGN KEY (MaNhom) REFERENCES NHOM(MaNhom) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BINHLUAN_BAIVIET (
    MaBL INT AUTO_INCREMENT PRIMARY KEY,
    MaBaiViet INT NOT NULL,
    MaND INT NOT NULL,
    NoiDung TEXT NOT NULL,
    MaBL_Cha INT DEFAULT NULL,
    NgayBinhLuan DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaBaiViet) REFERENCES BAIVIET_NHOM(MaBaiViet) ON DELETE CASCADE,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE,
    FOREIGN KEY (MaBL_Cha) REFERENCES BINHLUAN_BAIVIET(MaBL) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS THEODOI (
    MaND_TheoDoi INT NOT NULL,
    MaND_DuocTheoDoi INT NOT NULL,
    NgayTheoDoi DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND_TheoDoi, MaND_DuocTheoDoi),
    FOREIGN KEY (MaND_TheoDoi) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaND_DuocTheoDoi) REFERENCES NGUOIDUNG(MaND)
);

CREATE TABLE IF NOT EXISTS NGUOIDUNG_MONHOC (
    MaND INT NOT NULL,
    MaMonHoc INT NOT NULL,
    NgayTheoDoi DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND, MaMonHoc),
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaMonHoc) REFERENCES MONHOC(MaMonHoc)
);

CREATE TABLE IF NOT EXISTS TRUONGHOC (
    MaTruong INT AUTO_INCREMENT PRIMARY KEY,
    TenTruong VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS KHOANGANH (
    MaKhoa INT AUTO_INCREMENT PRIMARY KEY,
    TenKhoa VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS RESET_PASSWORD_OTP (
    Email VARCHAR(255) PRIMARY KEY,
    OTP VARCHAR(10) NOT NULL,
    ExpiresAt DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS DELETE_ACCOUNT_OTP (
    Email VARCHAR(255) PRIMARY KEY,
    OTP VARCHAR(10) NOT NULL,
    ExpiresAt DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS GIAODICH_NAPXU (
    MaGD INT AUTO_INCREMENT PRIMARY KEY,
    MaND INT NOT NULL,
    SoTien INT NOT NULL,
    SoXu INT NOT NULL,
    TrangThai ENUM('ChoDuyet', 'DaDuyet', 'TuChoi') DEFAULT 'ChoDuyet',
    MaND_Duyet INT DEFAULT NULL,
    MaPromo INT DEFAULT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayDuyet DATETIME DEFAULT NULL,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaND_Duyet) REFERENCES NGUOIDUNG(MaND)
);

CREATE TABLE IF NOT EXISTS TAILIEU_DAMUA (
    MaND INT NOT NULL,
    MaTL INT NOT NULL,
    NgayMua DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaND, MaTL),
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaTL) REFERENCES TAILIEU(MaTL)
);

CREATE TABLE IF NOT EXISTS LICH_SU_XU (
    MaGD INT AUTO_INCREMENT PRIMARY KEY,
    MaND INT NOT NULL,
    LoaiGiaoDich ENUM('NapXu', 'MuaTaiLieu', 'BanTaiLieu', 'TruXuAdmin', 'ThuongXu', 'HoanXu', 'PhatXu') NOT NULL,
    SoXuThayDoi INT NOT NULL,
    MoTa TEXT,
    NgayGiaoDich DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND)
);

CREATE TABLE IF NOT EXISTS YEU_CAU_GIAO_VIEN (
    MaYeuCau INT AUTO_INCREMENT PRIMARY KEY,
    MaND INT NOT NULL,
    MinhChungURL VARCHAR(255) NOT NULL,
    TrangThai ENUM('ChoDuyet', 'DaDuyet', 'TuChoi') DEFAULT 'ChoDuyet',
    LyDoTuChoi TEXT DEFAULT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND)
);

CREATE TABLE IF NOT EXISTS PROMO_CODE (
    MaPromo INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    DiscountPercent INT NOT NULL,
    Description TEXT,
    IsActive BOOLEAN DEFAULT TRUE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS REFRESH_TOKENS (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    MaND INT NOT NULL,
    Token VARCHAR(500) NOT NULL,
    ExpiresAt DATETIME NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    Revoked BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CAIDAT_CHAT (
    MaND INT NOT NULL,
    MaND_DoiTac INT NOT NULL,
    DaGhim BOOLEAN DEFAULT FALSE,
    DaChan BOOLEAN DEFAULT FALSE,
    NgayXoa DATETIME DEFAULT NULL,
    PRIMARY KEY (MaND, MaND_DoiTac),
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE,
    FOREIGN KEY (MaND_DoiTac) REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TINNHAN (
    MaTN INT AUTO_INCREMENT PRIMARY KEY,
    NguoiGui INT NOT NULL,
    NguoiNhan INT NOT NULL,
    NoiDung TEXT NOT NULL,
    DaDoc BOOLEAN DEFAULT FALSE,
    NgayGui DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (NguoiGui) REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE,
    FOREIGN KEY (NguoiNhan) REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE
);
CREATE INDEX idx_tinnhan_gui_nhan ON TINNHAN(NguoiGui, NguoiNhan);

CREATE INDEX idx_tailieu_trangthai ON TAILIEU(TrangThaiKiemDuyet);
CREATE INDEX idx_tailieu_ngaydang ON TAILIEU(NgayDang);
CREATE INDEX idx_tailieu_mamonhoc ON TAILIEU(MaMonHoc);
CREATE INDEX idx_tailieu_nguoidang ON TAILIEU(MaND_NguoiDang);
CREATE FULLTEXT INDEX idx_tailieu_fulltext ON TAILIEU(TenTL, MoTa);

CREATE INDEX idx_nguoidung_trangthai ON NGUOIDUNG(TrangThai);
CREATE INDEX idx_nguoidung_vaitro ON NGUOIDUNG(VaiTro);
CREATE INDEX idx_nguoidung_email ON NGUOIDUNG(Email);

CREATE INDEX idx_baocaovipham_trangthai ON BAOCAOVIPHAM(TrangThai);
CREATE INDEX idx_baocaovipham_ngaybaocao ON BAOCAOVIPHAM(NgayBaoCao);

CREATE INDEX idx_giaodich_napxu_trangthai ON GIAODICH_NAPXU(TrangThai);
CREATE INDEX idx_giaodich_napxu_ngaytao ON GIAODICH_NAPXU(NgayTao);

CREATE INDEX idx_nhom_ngaytao ON NHOM(NgayTao);
CREATE TABLE IF NOT EXISTS TINNHAN_NHOM (
    MaTN INT AUTO_INCREMENT PRIMARY KEY,
    MaNhom INT NOT NULL,
    MaND_Gui INT NOT NULL,
    NoiDung TEXT NOT NULL,
    LoaiTinNhan ENUM('text', 'image', 'file') DEFAULT 'text',
    TraLoiCho_MaTN INT DEFAULT NULL,
    DaThuHoi BOOLEAN DEFAULT FALSE,
    DaChinhSua BOOLEAN DEFAULT FALSE,
    Reactions JSON DEFAULT NULL,
    NgayGui DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaNhom) REFERENCES NHOM(MaNhom) ON DELETE CASCADE,
    FOREIGN KEY (MaND_Gui) REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE,
    FOREIGN KEY (TraLoiCho_MaTN) REFERENCES TINNHAN_NHOM(MaTN) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS TINNHAN_NHOM_DA_XOA (
    MaTN INT NOT NULL,
    MaND INT NOT NULL,
    PRIMARY KEY (MaTN, MaND),
    FOREIGN KEY (MaTN) REFERENCES TINNHAN_NHOM(MaTN) ON DELETE CASCADE,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE
);
